### ISSUE TITLE
Data/ Model Download

### ISSUE THREAD

**Issue by erasmuss** [xiaqiong/DeepCID#2]
Trying to download the data/model is difficult because of language barrier and unable to download parts without installing unfamiliar software. Documentation would be helpful, and/or platform in English.

**Comment by aslankims** [comment]
I had faced up with the same problem. One of my Chinese friends helped me to download the data from Baidu, which is supporting domestic service only in China. If you still want to play with the data&model, please let me know to help you. 
Cheers.

**Comment by XiaqiongFan** [comment]
> 
> 
> Trying to download the data/model is difficult because of language barrier and unable to download parts without installing unfamiliar software. Documentation would be helpful, and/or platform in English.

I'm sorry for not responding in time. All models and some example data have been re-uploaded in Google driver (https://drive.google.com/drive/folders/1DzMqiJRPDaLn2PcFW_myY_p0PO_VVEpS?usp=sharing). Now you can run the code, reload all models and implement prediction. Feel free to contact us if we can be of any further assistance.

**Comment by XiaqiongFan** [comment]
> 
> 
> I had faced up with the same problem. One of my Chinese friends helped me to download the data from Baidu, which is supporting domestic service only in China. If you still want to play with the data&model, please let me know to help you.
> Cheers.

Apologies for the inconvenience. All models and some example data have been re-uploaded in Google driver (https://drive.google.com/drive/folders/1DzMqiJRPDaLn2PcFW_myY_p0PO_VVEpS?usp=sharing). Feel free to contact us if we can be of any further assistance.
